-- Baseline schema: expresses exactly what Hibernate (ddl-auto: update) mapped from the entities
-- in app.rubric and app.evaluation.persistence, captured by inspecting the schema Hibernate 6.6
-- actually builds for those entities against Postgres 16 rather than hand-derived from the
-- annotations, so column names, types, nullability and identity strategy all match what
-- `ddl-auto: validate` will check on startup from here on.

CREATE TABLE rubrics (
    version    integer                  NOT NULL,
    assignment character varying(255)   NOT NULL,
    language   character varying(255)   NOT NULL,
    note       character varying(2000),
    CONSTRAINT pk_rubrics PRIMARY KEY (version)
);

CREATE TABLE criteria (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    criterion_key  character varying(255)  NOT NULL,
    name           character varying(255)  NOT NULL,
    weight         integer                 NOT NULL,
    description    character varying(2000) NOT NULL,
    rubric_version integer                 NOT NULL,
    -- Order of this Criterion within its Rubric's criteria list. Set by Hibernate in a follow-up
    -- UPDATE after the row is inserted (it owns the inverse side of Rubric.criteria), so it is
    -- nullable between those two statements.
    "position"     integer,
    CONSTRAINT pk_criteria PRIMARY KEY (id),
    CONSTRAINT fk_criteria_rubric FOREIGN KEY (rubric_version) REFERENCES rubrics (version)
);

CREATE TABLE criterion_sources (
    criterion_id bigint                 NOT NULL,
    source       character varying(255) NOT NULL,
    "position"   integer                NOT NULL,
    CONSTRAINT pk_criterion_sources PRIMARY KEY (criterion_id, "position"),
    CONSTRAINT fk_criterion_sources_criterion FOREIGN KEY (criterion_id) REFERENCES criteria (id)
);

CREATE TABLE criterion_levels (
    criterion_id bigint                  NOT NULL,
    level_name   character varying(255)  NOT NULL,
    descriptor   character varying(2000) NOT NULL,
    CONSTRAINT pk_criterion_levels PRIMARY KEY (criterion_id, level_name),
    CONSTRAINT fk_criterion_levels_criterion FOREIGN KEY (criterion_id) REFERENCES criteria (id)
);

CREATE TABLE evaluations (
    id              uuid                     NOT NULL,
    rubric_version  integer                  NOT NULL,
    provider        character varying(255)   NOT NULL,
    model           character varying(255)   NOT NULL,
    suggested_grade character varying(255)   NOT NULL,
    created_at      timestamp(6) with time zone NOT NULL,
    document        jsonb                    NOT NULL,
    CONSTRAINT pk_evaluations PRIMARY KEY (id)
);
