-- Replaces the single seeded Rubric with the Assignment aggregate: an Assignment belongs to
-- exactly one Educator, has exactly one mutable Draft, and any number of frozen, published
-- AssignmentVersions. Rubric stops being a table of its own and becomes a value read off a
-- Draft's or an AssignmentVersion's own Criteria.
--
-- The evaluations truncated below are pre-auth development test runs recorded against the one
-- Rubric this migration removes. None of them can be re-attributed to an Educator or an
-- Assignment — neither existed yet when they were produced — so a forward migration that
-- invented an owner for them was rejected: it would be written and debugged for data nobody has
-- ever queried and that stopped meaning anything the moment auth landed.
TRUNCATE TABLE evaluations;

DROP TABLE criterion_levels;
DROP TABLE criterion_sources;
DROP TABLE criteria;
DROP TABLE rubrics;

CREATE TABLE drafts (
    id                uuid                     NOT NULL,
    assessment_stance character varying(4000)  NOT NULL DEFAULT '',
    CONSTRAINT pk_drafts PRIMARY KEY (id)
);

CREATE TABLE assignments (
    id                      uuid                        NOT NULL,
    educator_id             uuid                        NOT NULL,
    title                   character varying(255)      NOT NULL,
    deleted                 boolean                     NOT NULL DEFAULT false,
    next_criterion_sequence integer                     NOT NULL DEFAULT 1,
    draft_id                uuid                        NOT NULL,
    created_at              timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_assignments PRIMARY KEY (id),
    CONSTRAINT fk_assignments_educator FOREIGN KEY (educator_id) REFERENCES educators (id),
    CONSTRAINT fk_assignments_draft FOREIGN KEY (draft_id) REFERENCES drafts (id),
    CONSTRAINT uq_assignments_draft UNIQUE (draft_id)
);

CREATE TABLE assignment_versions (
    id                uuid                        NOT NULL,
    assignment_id     uuid                        NOT NULL,
    version_number    integer                     NOT NULL,
    assessment_stance character varying(4000)     NOT NULL DEFAULT '',
    created_at        timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_assignment_versions PRIMARY KEY (id),
    CONSTRAINT fk_assignment_versions_assignment FOREIGN KEY (assignment_id) REFERENCES assignments (id),
    CONSTRAINT uq_assignment_versions_number UNIQUE (assignment_id, version_number)
);

-- A Criterion hangs off a Draft or off an AssignmentVersion, never both — the two foreign keys
-- below are nullable individually but exactly one is populated on any given row.
CREATE TABLE criteria (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    criterion_key         character varying(255)  NOT NULL,
    name                  character varying(255)  NOT NULL,
    weight                integer                 NOT NULL,
    description           character varying(2000) NOT NULL,
    draft_id              uuid,
    assignment_version_id uuid,
    "position"            integer,
    CONSTRAINT pk_criteria PRIMARY KEY (id),
    CONSTRAINT fk_criteria_draft FOREIGN KEY (draft_id) REFERENCES drafts (id),
    CONSTRAINT fk_criteria_version FOREIGN KEY (assignment_version_id) REFERENCES assignment_versions (id),
    CONSTRAINT chk_criteria_exactly_one_parent CHECK (
        (draft_id IS NOT NULL) <> (assignment_version_id IS NOT NULL)
    )
);

CREATE TABLE criterion_source_references (
    criterion_id bigint                 NOT NULL,
    source       character varying(255) NOT NULL,
    "position"   integer                NOT NULL,
    CONSTRAINT pk_criterion_source_references PRIMARY KEY (criterion_id, "position"),
    CONSTRAINT fk_criterion_source_references_criterion FOREIGN KEY (criterion_id) REFERENCES criteria (id)
);

CREATE TABLE criterion_levels (
    criterion_id bigint                  NOT NULL,
    level_name   character varying(255)  NOT NULL,
    descriptor   character varying(2000) NOT NULL,
    CONSTRAINT pk_criterion_levels PRIMARY KEY (criterion_id, level_name),
    CONSTRAINT fk_criterion_levels_criterion FOREIGN KEY (criterion_id) REFERENCES criteria (id)
);
